<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Eru.Adapters</AssemblyName>
    <RootNamespace>Eru.Adapters</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Eru.Domain/Eru.Domain.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SimpleExec" Version="13.*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Paths.fs" />
    <Compile Include="Serialization.fs" />
    <Compile Include="ConfigAdapter.fs" />
    <Compile Include="LockFileAdapter.fs" />
    <Compile Include="GitAdapter.fs" />
    <Compile Include="ManifestAdapter.fs" />
    <Compile Include="AdapterDeps.fs" />
  </ItemGroup>
</Project>
